In [1]:
import requests
import pandas as pd

In [2]:
years = list(range(2022, 1991,-1))
len(years)

31

In [3]:
url = 'https://www.basketball-reference.com/leagues/NBA_1992_totals.html'
data = requests.get(url)

In [4]:
matches = pd.read_html(data.text, match='Player Totals Table')[0]

In [5]:
matches

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Alaa Abdelnaby,PF,23,POR,71,1,934,178,361,...,.752,81,179,260,30,25,16,66,132,432
1,2,Mahmoud Abdul-Rauf,PG,22,DEN,81,11,1538,356,845,...,.870,22,92,114,192,44,4,117,130,837
2,3,Mark Acres,C,29,ORL,68,6,926,78,151,...,.761,97,155,252,22,25,15,33,140,208
3,4,Michael Adams,PG,29,WSB,78,78,2795,485,1233,...,.869,58,252,310,594,145,9,212,162,1408
4,5,Rafael Addison,SF,27,NJN,76,8,1175,187,432,...,.737,65,100,165,68,28,28,46,109,444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,384,Orlando Woolridge,SF,32,DET,82,61,2113,452,907,...,.683,109,151,260,88,41,33,133,154,1146
473,385,James Worthy*,SF,30,LAL,54,54,2108,450,1007,...,.814,98,207,305,252,76,23,127,89,1075
474,386,Danny Young,PG,29,TOT,62,5,1023,100,255,...,.851,16,59,75,172,46,4,47,53,280
475,386,Danny Young,PG,29,POR,18,0,134,16,40,...,.714,0,9,9,20,6,0,5,6,45
476,386,Danny Young,PG,29,LAC,44,5,889,84,215,...,.887,16,50,66,152,40,4,42,47,235

In [6]:
player_stats = list()

for year in years:
    urls = (f'https://www.basketball-reference.com/leagues/NBA_{year}_totals.html')
    data = requests.get(urls)
    player_stat = pd.read_html(data.text, match='Player Totals Table')[0]
    player_stat['Year'] = year 
    player_stats.append(player_stat)

In [7]:
player_stats[0].head() #NBA Player Stats from 2021-22 Season

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Precious Achiuwa,C,22,TOR,73,28,1725,265,603,...,146,327,473,82,37,41,84,151,664,2022
1,2,Steven Adams,C,28,MEM,76,75,1999,210,384,...,349,411,760,256,65,60,115,153,528,2022
2,3,Bam Adebayo,C,24,MIA,56,56,1825,406,729,...,137,427,564,190,80,44,148,171,1068,2022
3,4,Santi Aldama,PF,21,MEM,32,0,360,53,132,...,33,54,87,21,6,10,16,36,132,2022
4,5,LaMarcus Aldridge,C,36,BRK,47,12,1050,252,458,...,73,185,258,42,14,47,44,78,607,2022

In [8]:
player_stats[30].head() #NBA Player Stats from 1991-92 Season

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,23,POR,71,1,934,178,361,...,81,179,260,30,25,16,66,132,432,1992
1,2,Mahmoud Abdul-Rauf,PG,22,DEN,81,11,1538,356,845,...,22,92,114,192,44,4,117,130,837,1992
2,3,Mark Acres,C,29,ORL,68,6,926,78,151,...,97,155,252,22,25,15,33,140,208,1992
3,4,Michael Adams,PG,29,WSB,78,78,2795,485,1233,...,58,252,310,594,145,9,212,162,1408,1992
4,5,Rafael Addison,SF,27,NJN,76,8,1175,187,432,...,65,100,165,68,28,28,46,109,444,1992

In [9]:
type(player_stats)

list

In [12]:
len(player_stats)

31

In [10]:
nba_player_stats_1992_2022 = pd.concat(player_stats)

In [11]:
nba_player_stats_1992_2022.to_csv('nba_player_stats_1992-2022.csv')